### ISSUE TITLE
Links not working in ss iptv(linux tv) but works in mobile vlc

### ISSUE THREAD

**Issue by AmmuBhai22** [sabbiriptv/Toffee-IPTV#1]
Hello Thanks a lot for your servers , but i had an issue and thought you could solve it . Actually I was trying to play the m3u8 in ss iptv in my linux tv which only have ss iptv to play m3u8 links . Now ss iptv was able to play SonyLIV and jio links but whenever i try to play the toffee tv links it just shows error basically network error and similar error is found if i test it on the following web player
https://m3u8play.dev/?url=https://toffee.sabbirhasan.trial.rocks/auto/cartoon_network_sd.m3u8
Upon researching a bit on network i found that maybe cors is the problem 
Can you please help me out with it 
Thanks

**Comment by sabbiriptv** [comment]
Thank you for reaching out.

Yes, you are exactly right that the problem is related to CORS. Fixing it is not a difficult task, but as my exam is currently ongoing, I cannot access my desktop. Therefore, I will have to fix it after the exam finishes on June 22nd. If I am able to fix it before that date, I will close this issue and let you know.

**Comment by AmmuBhai22** [comment]
Thanks sir for your reply

**Comment by sabbiriptv** [comment]
Hey There,
I've Uploaded Another M3U Which Is CORS Free Version Try To Use That ❤
